# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
      - master
 paths:
     include:
         - api/*
         - app/*
         - helptexts/*
         - kdvelements/*
         - web/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 12.x'
  inputs:
    versionSpec: 12.x
    checkLatest: true

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- script: |
   git config user.email "regobs@nve.no" 
   git config user.name "Azure CI Pipeline"
  displayName: 'Set git user'

- task: Npm@1
  displayName: 'npm version patch'
  inputs:
    command: custom
    verbose: false
    customCommand: 'version patch --force -m "Azure Pipeline Release (CI)"'
- task: Npm@1
  displayName: 'npm publish'
  inputs:
    command: custom
    verbose: false
    customCommand: 'publish --access public'
    customEndpoint: 'NPM public registry'
    publishEndpoint: 'NPM public registry'

- script: |
   git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin
  displayName: 'Git push new package version and tags'
- task: GitHubRelease@1
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: 'regObs Github'
